# Generated by Django 4.2.14 on 2024-12-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpost',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
