# Generated by Django 4.1 on 2023-11-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_about_user_alter_userprofile_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_content',
            field=models.CharField(max_length=5000),
        ),
    ]
