# Generated by Django 4.1 on 2023-11-28 18:46

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userpost_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='comments',
            field=models.JSONField(default=home.models.JsonDefaultComment, null=True),
        ),
    ]
